### ISSUE TITLE
Handle hyphens in interface_name

### ISSUE THREAD

**Issue by matt-mazzucato** [astarte-platform/astarte#184] opened 2020-01-10 15:28 UTC
Astarte core currently allows hyphens in the interface_name according to https://github.com/astarte-platform/astarte_core/pull/10
As discussed in https://github.com/astarte-platform/astarte_core/issues/7, the new naming convention must be handled while mapping the interface onto the table name.

**Comment by bettio** [comment] 2020-01-15 11:00
Duplicate of https://github.com/astarte-platform/astarte/issues/96

**Closed by bettio** 2020-01-15 11:00 UTC
Labels: app:realm_management, blocking, database, discussion, duplicate
