### ISSUE TITLE
Avoid cluttering logs with health checks

### ISSUE THREAD

**Issue by drf** [astarte-platform/astarte#298] opened 2020-04-06 08:35 UTC
When looking at logs, health checks are logged also at info level everywhere. This clutters the logs quite extensively especially when following and tailing. Ideally, we should handle special cases for the `/health` endpoint, avoiding logging those calls or finding a different strategy.

**Comment by Pavinati** [comment] 2020-04-06 08:47
I think it's a duplicate of https://github.com/astarte-platform/astarte/issues/296

**Comment by rbino** [comment] 2020-04-06 08:48
Closing as duplicate

**Closed by rbino** 2020-04-06 08:48 UTC
Labels: API, duplicate, enhancement, user experience
