### ISSUE TITLE
Astarte might lose VerneMQ events and represent a wrong connection state

### ISSUE THREAD

**Issue by drf** [astarte-platform/astarte#270] opened 2020-03-05 22:29 UTC
In some unlucky cases, Astarte might lose some connection/disconnection events from VerneMQ (e.g.: VerneMQ restarts, a previously connected device doesn't reconnect). In those cases, the internal device state is represented as `connected=True` instead of `connected=False`.

Astarte should have a way to catch these occurrences and ensure the device connection state is always consistent.

**Comment by bettio** [comment] 2020-04-07 10:34
This bug is a duplicate of https://github.com/astarte-platform/astarte/issues/305 which contains a better description of the issue.

**Closed by bettio** 2020-04-07 10:34 UTC
Labels: bug
