### ISSUE TITLE
Discuss the possibility of adding device properties with object aggregation

### ISSUE THREAD

**Issue by rbino** [astarte-platform/astarte#541] opened 2021-02-23 11:34 UTC
Some usecases seem to map naturally to this pattern. While they can be implemented also with the existing infrastructure, it can be useful to discuss the possibility of adding the ability of installing interfaces that publish device properties with an object aggregation.

**Comment by bettio** [comment] 2021-04-30 10:42
Duplicate of #503

**Closed by bettio** 2021-04-30 10:42 UTC
Labels: app:appengine_api, app:data_updater_plant, app:realm_management, app:realm_management_api, discussion, duplicate, enhancement
