### ISSUE TITLE
Registering a Device documentation page has a broken link to "Pairing's Agent APIs"

### ISSUE THREAD

**Issue by bettio** [astarte-platform/astarte#324] opened 2020-04-10 15:54 UTC
[Registering a Device](https://docs.astarte-platform.org/0.11/035-register_device.html) has a broken link (`Pairing's Agent APIs`) to https://docs.astarte-platform.org/0.11/api/index.html?urls.primaryName=Pairing%20API#/agent .

**Comment by drf** [comment] 2020-04-13 06:54
Duplicate of #337

**Closed by drf** 2020-04-13 06:54 UTC
Labels: documentation
