### ISSUE TITLE
AppEngine queries on group devices do not work if the group name contains a forward slash '/'

### ISSUE THREAD

**Issue by Pavinati** [astarte-platform/astarte#904] opened 2024-02-16 15:45 UTC
#### Steps to replicate:
- create a group with a device and group name "abc/xyz"
- query the group devices and verify that the group exists and it contains the device id (GET `/groups/abc%252Fxyz/devices`)
- query the device status of interface data through the group endpoing (GET `/groups/abc%252Fxyz/devices/<device_id>/org.astarte-platform.genericsensors.Values`)

#### Expected result
The device data

#### Actual result
`{"errors":{"detail":"Device not found"}}`

**Comment by rbino** [comment] 2024-02-19 08:22
Why `%252F` and not `%2F`? How does this behave if you replace `%2F` in both cases above?

**Comment by Pavinati** [comment] 2024-02-19 09:31
Double encoding is used to avoid mistaking the `/` in `abc/xyz` as part of the path.
The fact that one query works on the other does not makes me think this was addressed in the past but not for every group query

**Comment by rbino** [comment] 2024-02-19 15:22
The issue is that [`InterfaseValuesByGroupController`](https://github.com/astarte-platform/astarte/blob/master/apps/astarte_appengine_api/lib/astarte_appengine_api_web/controllers/interface_values_by_group_controller.ex) does not decode the group name like [`DeviceStatusByGroupController` does](https://github.com/astarte-platform/astarte/blob/master/apps/astarte_appengine_api/lib/astarte_appengine_api_web/controllers/device_status_by_group_controller.ex#L36).

Easy fix: add that decoding. Better fix: scope all `/groups` APIs and make a plug that fixes `group_name` in a single place so we don't miss out on (potentially new) APIs there.

Marking this as Good first issue since it's quite trivial (also the test section of groups is not terrible so it's reasonable to also add a test for the fix to avoid regressions).

**Closed** 2024-03-22 15:12 UTC
Labels: bug, good first issue, app:appengine_api, app:trigger_engine
